name: latlng
description: Geodesy and Geographical calculations for Dart. Provides LatLong and Mercator projection (EPSG4326).
version: 0.2.0
homepage: https://github.com/xclud/dart_latlng

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.3
  lints: ^2.0.0
